#!/usr/bin/env bash

# exit when any command fails
set -e

# install xcode command line tools
xcode-select --install || true

# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /Users/chris/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/chris/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"


# iterm2
brew install --cask iterm2
brew install --cask openinterminal

# update command line tools
brew install zsh bash git

# dependencies of aliases or bin scripts
brew install jq

# in case it was not properly installed initialy
brew install git-delta

# fonts
brew install --cask homebrew/cask-fonts/font-cascadia-code homebrew/cask-fonts/font-cascadia-code-pl
brew install --cask homebrew/cask-fonts/font-cascadia-mono homebrew/cask-fonts/font-cascadia-mono-pl

# run `p10k configure` to install meslo font

# utils
brew install --cask rectangle

# passwords and gpg
brew install --cask keepassxc
brew install --cask gpg-suite

# Applications
brew install --cask notion

# Code
brew install nodejs corepack
brew install --cask visual-studio-code
brew install watchman

# performance benchmark tool
brew install hyperfine

# mongodb
brew tap mongodb/brew
brew install mongodb-community@6.0
# start mongo as a background process
brew services start mongodb-community@6.0
# stoppable: brew services stop mongodb-community@6.0

