#!/usr/bin/env bash

# exit when any command fails
set -e

# install xcode command line tools
xcode-select --install || true

# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
if [ ! -f /Users/chris/.zprofile ]; then
  touch /Users/chris/.zprofile
fi
echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /Users/chris/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/chris/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"


# iterm2
brew install --cask iterm2
brew install --cask openinterminal

# # zimfw https://github.com/zimfw/zimfw
# brew install --formula zimfw


brew tap homebrew/command-not-found
brew install zsh-syntax-highlighting
brew install zsh-autosuggestions
brew install pure


# update command line tools
brew install zsh bash git

# dependencies of aliases or bin scripts
brew install jq

# in case it was not properly installed initialy
brew install git-delta

# fonts
brew install --cask homebrew/cask-fonts/font-cascadia-code homebrew/cask-fonts/font-cascadia-code-pl
brew install --cask homebrew/cask-fonts/font-cascadia-mono homebrew/cask-fonts/font-cascadia-mono-pl

# brew install --cask font-meslo-lg-nerd-font

brew install --cask font-jetbrains-mono
brew install --cask font-sora

# utils
brew install --cask rectangle

# passwords
brew install --cask keepassxc

# Applications
brew install --cask notion

# Code
brew install nodejs
brew install --cask visual-studio-code
brew install watchman

# performance benchmark tool
brew install hyperfine

# mongodb
brew tap mongodb/brew
brew install mongodb-community@6.0
# start mongo as a background process
brew services start mongodb-community@6.0
# stoppable: brew services stop mongodb-community@6.0

